//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int eno { get; set; }
        public string ename { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<int> dno { get; set; }
    }
}
